General:
    comment: 
    seed: 2024
    fp16: True
    amp_level: O2
    precision: 16 
    multi_gpu_mode: dp
    gpus: [0]
    epochs: &epoch 200 
    grad_acc: 2
    frozen_bn: False
    patience: 10
    server: test #train #test
    log_path:

Data:
    dataset_name: tcga_data
    data_shuffle: False
    data_dir:
    label_dir: dataset_csv/tcga_lung_subtype/
    fold: 0
    nfold: 4
    prop: 0.2

    train_dataloader:
        batch_size: 1 
        num_workers: 8

    test_dataloader:
        batch_size: 1
        num_workers: 8

Model:
    name: TestModel8
    n_classes: 2


Optimizer:
    opt: lookahead_radam
    lr: 0.0002
    opt_eps: null 
    opt_betas: null
    momentum: null 
    weight_decay: 0.00001

Loss:
    base_loss: CrossEntropyLoss

